###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

  mariadb:
    image: mariadb:10.4
    container_name: mk-js-blog-mariadb
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=blg124
      - MYSQL_DATABASE=blog
      - MYSQL_USER=blog
      - MYSQL_PASSWORD=blg124
    ports:
      - "2078:3306"